#!/bin/sh
# Terraform Initialization Script
# Runs Terraform to configure Keycloak and Vault, outputs credentials for services
set -e

echo "=========================================="
echo "Terraform Infrastructure Setup"
echo "=========================================="

TERRAFORM_DIR="/terraform"
VAULT_CREDS="/vault/init/credentials.env"
OUTPUT_DIR="/terraform/output"

mkdir -p "$OUTPUT_DIR"

# Wait for Vault credentials
echo ""
echo "Waiting for Vault credentials..."
max_attempts=60
attempt=0
until [ -f "$VAULT_CREDS" ]; do
    attempt=$((attempt + 1))
    if [ $attempt -ge $max_attempts ]; then
        echo "ERROR: Vault credentials not found at ${VAULT_CREDS}"
        exit 1
    fi
    echo "  Attempt ${attempt}/${max_attempts}..."
    sleep 5
done
echo "Vault credentials found!"

# Source Vault credentials
. "$VAULT_CREDS"
export TF_VAR_vault_root_token="$VAULT_ROOT_TOKEN"

# Wait for Keycloak to be ready
echo ""
echo "Waiting for Keycloak to be ready..."
max_attempts=60
attempt=0
until wget -q --spider "${KEYCLOAK_URL}/health/ready" 2>/dev/null; do
    attempt=$((attempt + 1))
    if [ $attempt -ge $max_attempts ]; then
        echo "ERROR: Keycloak did not become ready in time"
        exit 1
    fi
    echo "  Attempt ${attempt}/${max_attempts}..."
    sleep 5
done
echo "Keycloak is ready!"

# Set Terraform variables from environment
export TF_VAR_keycloak_url="${KEYCLOAK_URL}"
export TF_VAR_keycloak_admin_user="${KEYCLOAK_ADMIN:-admin}"
export TF_VAR_keycloak_admin_password="${KEYCLOAK_ADMIN_PASSWORD:-admin}"
export TF_VAR_portal_host="${FSC_PORTAL_HOST:-portal.fsc.orb.local}"
export TF_VAR_keycloak_realm="${FSC_KEYCLOAK_REALM:-faux-splunk}"
export TF_VAR_default_admin_email="${FSC_DEFAULT_ADMIN_EMAIL:-admin@faux-splunk.local}"
export TF_VAR_default_admin_password="${FSC_DEFAULT_ADMIN_PASSWORD:-admin}"
export TF_VAR_vault_address="${VAULT_ADDR:-http://vault:8200}"
export TF_VAR_vault_oidc_secret="${FSC_VAULT_OIDC_SECRET:-vault-oidc-secret}"
export TF_VAR_concourse_oidc_secret="${FSC_CONCOURSE_OIDC_SECRET:-concourse-oidc-secret}"

cd "$TERRAFORM_DIR"

# Initialize Terraform
echo ""
echo "Initializing Terraform..."
terraform init -input=false

# Plan
echo ""
echo "Planning Terraform changes..."
terraform plan -input=false -out=tfplan

# Apply
echo ""
echo "Applying Terraform configuration..."
terraform apply -input=false -auto-approve tfplan

# Export outputs for other services
echo ""
echo "Exporting Terraform outputs..."

# Get Concourse AppRole credentials
CONCOURSE_ROLE_ID=$(terraform output -raw concourse_vault_role_id 2>/dev/null || echo "")
CONCOURSE_SECRET_ID=$(terraform output -raw concourse_vault_secret_id 2>/dev/null || echo "")

# Get FSC API AppRole credentials
FSC_API_ROLE_ID=$(terraform output -raw fsc_api_vault_role_id 2>/dev/null || echo "")
FSC_API_SECRET_ID=$(terraform output -raw fsc_api_vault_secret_id 2>/dev/null || echo "")

# Write Concourse credentials
cat > "$OUTPUT_DIR/concourse.env" <<EOF
# Concourse Vault AppRole Credentials
# Generated by Terraform
CONCOURSE_VAULT_AUTH_PARAM=role_id:${CONCOURSE_ROLE_ID},secret_id:${CONCOURSE_SECRET_ID}
VAULT_ROLE_ID=${CONCOURSE_ROLE_ID}
VAULT_SECRET_ID=${CONCOURSE_SECRET_ID}
EOF
chmod 600 "$OUTPUT_DIR/concourse.env"

# Write FSC API credentials
cat > "$OUTPUT_DIR/fsc-api.env" <<EOF
# FSC API Vault AppRole Credentials
# Generated by Terraform
FSC_VAULT_ROLE_ID=${FSC_API_ROLE_ID}
FSC_VAULT_SECRET_ID=${FSC_API_SECRET_ID}
EOF
chmod 600 "$OUTPUT_DIR/fsc-api.env"

# Write combined outputs
cat > "$OUTPUT_DIR/all-outputs.env" <<EOF
# All Terraform Outputs
# Generated by Terraform

# Keycloak
KEYCLOAK_REALM=$(terraform output -raw keycloak_realm_name 2>/dev/null || echo "")
SAML_METADATA_URL=$(terraform output -raw saml_metadata_url 2>/dev/null || echo "")
OIDC_ISSUER_URL=$(terraform output -raw oidc_issuer_url 2>/dev/null || echo "")

# Vault
VAULT_KV_PATH=$(terraform output -raw vault_kv_path 2>/dev/null || echo "")
VAULT_TRANSIT_KEY=$(terraform output -raw vault_transit_key 2>/dev/null || echo "")

# Concourse AppRole
CONCOURSE_VAULT_ROLE_ID=${CONCOURSE_ROLE_ID}
CONCOURSE_VAULT_SECRET_ID=${CONCOURSE_SECRET_ID}

# FSC API AppRole
FSC_VAULT_ROLE_ID=${FSC_API_ROLE_ID}
FSC_VAULT_SECRET_ID=${FSC_API_SECRET_ID}
EOF
chmod 600 "$OUTPUT_DIR/all-outputs.env"

echo ""
echo "=========================================="
echo "Terraform Setup Complete!"
echo "=========================================="
echo ""
echo "Outputs written to:"
echo "  - ${OUTPUT_DIR}/concourse.env"
echo "  - ${OUTPUT_DIR}/fsc-api.env"
echo "  - ${OUTPUT_DIR}/all-outputs.env"
echo ""
