#!/bin/sh
# Vault Initialization Script
# Initializes Vault and outputs credentials for Terraform
set -e

VAULT_ADDR="${VAULT_ADDR:-http://vault:8200}"
INIT_OUTPUT="/vault/init/init.json"
CREDS_OUTPUT="/vault/init/credentials.env"

echo "=========================================="
echo "Vault Initialization"
echo "=========================================="
echo "Vault Address: ${VAULT_ADDR}"

# Wait for Vault to be available
echo ""
echo "Waiting for Vault to be available..."
max_attempts=60
attempt=0
until wget -q --spider "${VAULT_ADDR}/v1/sys/health?standbyok=true&uninitcode=200&sealedcode=200" 2>/dev/null; do
    attempt=$((attempt + 1))
    if [ $attempt -ge $max_attempts ]; then
        echo "ERROR: Vault did not become available in time"
        exit 1
    fi
    echo "  Attempt ${attempt}/${max_attempts}..."
    sleep 5
done
echo "Vault is available!"

# Check initialization status
echo ""
echo "Checking Vault initialization status..."
INIT_STATUS=$(wget -q -O - "${VAULT_ADDR}/v1/sys/health?standbyok=true&uninitcode=200&sealedcode=200" 2>/dev/null || echo '{"initialized":false}')

if echo "$INIT_STATUS" | grep -q '"initialized":true'; then
    echo "Vault is already initialized"

    # Check if we have stored credentials
    if [ -f "$INIT_OUTPUT" ]; then
        echo "Found existing credentials at ${INIT_OUTPUT}"
        ROOT_TOKEN=$(cat "$INIT_OUTPUT" | sed -n 's/.*"root_token":"\([^"]*\)".*/\1/p')
        UNSEAL_KEY=$(cat "$INIT_OUTPUT" | sed -n 's/.*"keys_base64":\["\([^"]*\)".*/\1/p')
    else
        echo "ERROR: Vault is initialized but no credentials found"
        echo "Please manually unseal Vault and provide credentials"
        exit 1
    fi
else
    echo "Initializing Vault..."

    # Initialize with 1 key share for dev (use 5 for production)
    INIT_RESPONSE=$(wget -q -O - --post-data '{"secret_shares":1,"secret_threshold":1}' \
        --header="Content-Type: application/json" \
        "${VAULT_ADDR}/v1/sys/init" 2>/dev/null)

    if [ -z "$INIT_RESPONSE" ]; then
        echo "ERROR: Failed to initialize Vault"
        exit 1
    fi

    # Save init response
    echo "$INIT_RESPONSE" > "$INIT_OUTPUT"
    chmod 600 "$INIT_OUTPUT"

    ROOT_TOKEN=$(echo "$INIT_RESPONSE" | sed -n 's/.*"root_token":"\([^"]*\)".*/\1/p')
    UNSEAL_KEY=$(echo "$INIT_RESPONSE" | sed -n 's/.*"keys_base64":\["\([^"]*\)".*/\1/p')

    echo "Vault initialized successfully!"
fi

# Check seal status
echo ""
echo "Checking seal status..."
SEAL_STATUS=$(wget -q -O - "${VAULT_ADDR}/v1/sys/seal-status" 2>/dev/null || echo '{"sealed":true}')

if echo "$SEAL_STATUS" | grep -q '"sealed":true'; then
    echo "Vault is sealed, unsealing..."

    UNSEAL_RESPONSE=$(wget -q -O - --post-data "{\"key\":\"${UNSEAL_KEY}\"}" \
        --header="Content-Type: application/json" \
        "${VAULT_ADDR}/v1/sys/unseal" 2>/dev/null)

    if echo "$UNSEAL_RESPONSE" | grep -q '"sealed":false'; then
        echo "Vault unsealed successfully!"
    else
        echo "ERROR: Failed to unseal Vault"
        exit 1
    fi
else
    echo "Vault is already unsealed"
fi

# Export credentials for Terraform
echo ""
echo "Exporting credentials..."
cat > "$CREDS_OUTPUT" <<EOF
# Vault Credentials - Generated by init-vault.sh
# DO NOT COMMIT THIS FILE
VAULT_ROOT_TOKEN=${ROOT_TOKEN}
VAULT_UNSEAL_KEY=${UNSEAL_KEY}
EOF
chmod 600 "$CREDS_OUTPUT"

echo ""
echo "=========================================="
echo "Vault Initialization Complete!"
echo "=========================================="
echo "Root token saved to: ${INIT_OUTPUT}"
echo "Credentials exported to: ${CREDS_OUTPUT}"
echo ""
